name: Build and Push to Docker Hub

on:
  workflow_dispatch: # 允许手动触发

# 明确指定权限
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # 指定环境名称
    environment: "default"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Echo secrets availability
        run: |
          echo "检查 secrets 是否可用（不显示实际值）："
          if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "DOCKERHUB_USERNAME 已设置"
          else
            echo "DOCKERHUB_USERNAME 未设置"
          fi

          if [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "DOCKERHUB_TOKEN 已设置"
          else
            echo "DOCKERHUB_TOKEN 未设置"
          fi

      # 使用固定的用户名
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate build timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            walkcat/gcp-graph-server:latest
            walkcat/gcp-graph-server:${{ steps.timestamp.outputs.timestamp }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
